// ===== AL NAFAY FRAGRANCE - PRODUCT DATABASE =====
// To add/edit products, update this file or use the Admin Panel

const PRODUCTS = [
  // BEST SELLERS
  {
    id: 1,
    name: "Acqua Di Gio Parfum",
    brand: "Giorgio Armani",
    category: "EDP",
    type: "Men",
    price: 12500,
    oldPrice: 16000,
    badge: "-22%",
    emoji: "🔵",
    description: "A fresh and aquatic masterpiece. The iconic Acqua Di Gio reimagined as an intense parfum with deep mineral notes and precious woods.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 2,
    name: "Bleu De Chanel EDP",
    brand: "Chanel",
    category: "EDP",
    type: "Men",
    price: 22000,
    oldPrice: null,
    badge: null,
    emoji: "🔷",
    description: "An aromatic-woody fragrance for the man who defies convention. Fresh citrus opens to a clean, warm base of sandalwood and cedar.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 3,
    name: "N°5 Eau de Parfum",
    brand: "Chanel",
    category: "EDP",
    type: "Women",
    price: 19500,
    oldPrice: null,
    badge: null,
    emoji: "🌸",
    description: "The legendary fragrance that has defined femininity for over a century. A timeless bouquet of aldehydes, jasmine, and rose.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 4,
    name: "Eternity Aromatic Essence EDP",
    brand: "Calvin Klein",
    category: "EDP",
    type: "Men",
    price: 8500,
    oldPrice: 11000,
    badge: "-23%",
    emoji: "🌿",
    description: "A bold, intense aromatic essence with notes of mint, mandarin, and woody musks. Modern masculinity in a bottle.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 5,
    name: "Stronger With You EDP",
    brand: "Giorgio Armani",
    category: "EDP",
    type: "Men",
    price: 14000,
    oldPrice: null,
    badge: null,
    emoji: "💛",
    description: "A warm and sensual oriental fragrance. Sweet cardamom and chestnut blend with a musky, woody base.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 6,
    name: "Oud Royal Intense",
    brand: "Al Nafay",
    category: "Oud",
    type: "Unisex",
    price: 6500,
    oldPrice: 9000,
    badge: "-28%",
    emoji: "🌰",
    description: "Our signature Oud blend - deep, rich, and captivating. A luxurious blend of pure oud wood, rose, and amber.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 7,
    name: "Libre EDP",
    brand: "Yves Saint Laurent",
    category: "EDP",
    type: "Women",
    price: 17500,
    oldPrice: null,
    badge: null,
    emoji: "💜",
    description: "An ode to freedom. A vibrant floral fragrance combining lavender flowers with a rich base of vanilla and musk.",
    isBestSeller: true,
    isNew: false
  },
  {
    id: 8,
    name: "Burberry Weekend EDT",
    brand: "Burberry",
    category: "EDT",
    type: "Men",
    price: 9500,
    oldPrice: null,
    badge: null,
    emoji: "🟫",
    description: "Fresh and vibrant. Apple, mandarin, and cedar create an effortlessly relaxed weekend fragrance.",
    isBestSeller: true,
    isNew: false
  },

  // NEW ARRIVALS
  {
    id: 9,
    name: "Al Nafay Midnight Oud",
    brand: "Al Nafay",
    category: "Oud",
    type: "Unisex",
    price: 7200,
    oldPrice: null,
    badge: "NEW",
    emoji: "🖤",
    description: "The newest addition to our exclusive Oud collection. Dark, mysterious, with notes of black oud, leather, and smoky amber.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 10,
    name: "Rose Garden Gift Set",
    brand: "Al Nafay",
    category: "Gift Set",
    type: "Women",
    price: 12000,
    oldPrice: 15000,
    badge: "NEW",
    emoji: "🎁",
    description: "A beautifully curated gift set featuring three floral fragrances: Rose, Jasmine & Lily of the Valley. Perfect for gifting.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 11,
    name: "Dior Sauvage EDP",
    brand: "Dior",
    category: "EDP",
    type: "Men",
    price: 18000,
    oldPrice: null,
    badge: "NEW",
    emoji: "⚫",
    description: "Raw, noble, and wild. Bergamot, pepper and ambroxan come together in this modern masculine classic.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 12,
    name: "Versace Eros EDP",
    brand: "Versace",
    category: "EDP",
    type: "Men",
    price: 10500,
    oldPrice: 13000,
    badge: "NEW",
    emoji: "💚",
    description: "Inspired by the Greek God of Love. Fresh mint, Italian lemon, and green apple, with a heart of tonka bean and vetiver.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 13,
    name: "Al Nafay Rose Silk EDP",
    brand: "Al Nafay",
    category: "EDP",
    type: "Women",
    price: 5500,
    oldPrice: null,
    badge: "NEW",
    emoji: "🌹",
    description: "A silky, feminine blend of Bulgarian rose, white musk, and sandalwood. Our premium creation for the modern woman.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 14,
    name: "Tom Ford Black Orchid",
    brand: "Tom Ford",
    category: "EDP",
    type: "Unisex",
    price: 24000,
    oldPrice: null,
    badge: "NEW",
    emoji: "🌑",
    description: "A luxurious and sensual fragrance. Dark black truffle, ylang ylang, and blackcurrant over a rich base of patchouli and incense.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 15,
    name: "Davidoff Cool Water EDT",
    brand: "Davidoff",
    category: "EDT",
    type: "Men",
    price: 7800,
    oldPrice: 9500,
    badge: "-18%",
    emoji: "💧",
    description: "The classic aquatic fragrance. Fresh greens, sea freshness, and woody notes create a timeless masculine scent.",
    isBestSeller: false,
    isNew: true
  },
  {
    id: 16,
    name: "Oriental Oud Gift Box",
    brand: "Al Nafay",
    category: "Gift Set",
    type: "Unisex",
    price: 15000,
    oldPrice: 18000,
    badge: "NEW",
    emoji: "🎀",
    description: "Our premium Oriental Gift Box contains 5 miniature Oud fragrances in a luxury presentation box. The perfect gift.",
    isBestSeller: false,
    isNew: true
  }
];
